# Generated by Django 5.1.7 on 2025-10-30 07:32

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('quantity', models.FloatField(default=1)),
                ('quantity_type', models.CharField(choices=[('Gram', 'Gram'), ('Liter', 'Liter'), ('Count', 'Count')], default='Count', max_length=10)),
                ('purchased', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to='family.familymembership')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grocery_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='grocery_ite_name_989450_idx'), models.Index(fields=['purchased'], name='grocery_ite_purchas_b91c38_idx'), models.Index(fields=['quantity_type'], name='grocery_ite_quantit_73a9ae_idx')],
            },
        ),
    ]
