# Generated by Django 5.1.7 on 2025-10-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='price',
        ),
    ]
