# Generated by Django 5.1.7 on 2025-10-31 18:21

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('grocery', '0002_remove_groceryitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='family_membership',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='purchased_by',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_created_by', to=settings.AUTH_USER_MODEL)),
                ('family_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_lists', to='family.familymembership')),
            ],
            options={
                'db_table': 'grocery_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='grocery_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grocery.grocerylist'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='grocerylist',
            index=models.Index(fields=['name'], name='grocery_lis_name_f66359_idx'),
        ),
    ]
